dbConnectionUri: "mongodb://localhost:27017/databaseName"
domain: "http://localhost:8080"
relyingParties:
  - name: "Test App"
    clientId: "rp1"
    clientSecret: "DeepestAndDarkest"
    description: "Relying Party Test App"
    icon: "https://placekitten.com/200/200"
    backgroundImage: "https://placekitten.com/800/300"
    theme:
      cta: "#0B669D"
      primary: "#045199"
      header: "#0979c4"
    redirectUri: "http://localhost:3000"
    scopes:
      - name: "openid"
        description: "Open ID Connect"
    vprQuery: >
      {
        "query": {
          "type": "QueryByExample",
          "credentialQuery": {
            "reason": "Please present your Verifiable Credential to complete the verification process.",
            "example": {
              "@context": [
                "https://www.w3.org/2018/credentials/v1",
                "https://w3id.org/citizenship/v1"
              ],
              "type": [
                "PermanentResidentCard"
              ]
            }
          }
        }
      }
    claims:
      - name: "email"
        description: "Your email address"
        claimIri: "https://schema.org/email"
    workflow:
      type: vc-api
      baseUrl: https://example.org/exchanges/123
      capability: "example"
      clientSecret: "example"
defaultLanguage: en
translations:
  en: 
    loginCta: "Login with your credential wallet"
    loginExplain: "To login with your credential wallet, you will need to have the credential wallet app <with configurable URL to app stores> installed"
    appInstallExplain: "If you don't have a credential wallet yet, you can get one by downloading the credential wallet app <with configurable URL to app stores>"
    appCta: "Open wallet app"
    qrExplain: "Looking for a QR Code to scan with you wallet app instead?"
    qrPageExplain: "Scan the following QR Code with your wallet app."
    qrCta: "Scan the following QR Code with your wallet app"
    copyright: "Powered by OpenCred"
  fr:
    loginCta: "Se connecter avec son portefeuille de titres"
    loginExplain: "Pour vous connecter avec votre credential wallet, vous devez avoir installé l'application credential wallet <avec une URL configurable vers les app stores>"
    appInstallExplain: "Si vous n'avez pas encore de porte-monnaie électronique, vous pouvez en obtenir un en téléchargeant l'application credential wallet <avec une URL configurable vers les magasins d'applications>"
    appCta: "Ouvrir l'application portefeuille"
    qrExplain: "Vous cherchez un code QR à scanner avec l'application de votre portefeuille?"
    qrCta: "Scannez le code QR suivant avec l'application de votre portefeuille"
    copyright: "Développé par OpenCred"
