name: Veracode SCA

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan repository with Veracode SCA

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
          # workspace slug is specific to DB repos
          SRCCLR_WORKSPACE_SLUG: rZZUVVeV
        uses: veracode/veracode-sca@v2.0.65
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: true
